//
// MRTreasure.cs
//
// Author:
//       Steve Jakab <>
//
// Copyright (c) 2014 Steve Jakab
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Text;
using AssemblyCSharp;

public class MRTreasure : MRItem
{
	public bool IsGreatTreasure
	{
		get{
			return mIsGreatTreasure;
		}
	}

	public bool IsLargeTreasure
	{
		get{
			return mIsLargeTreasure;
		}
	}

	public bool IsTwiT
	{
		get{
			return mIsTwiT;
		}
	}

	public bool Hidden
	{
		get{
			return mHidden;
		}

		set{
			mHidden = value;
		}
	}

	#region Methods

	public MRTreasure ()
	{
	}

	public MRTreasure(JSONObject data, int index) : base((JSONObject)data["MRItem"], index)
	{
		mHidden = true;

		mIsGreatTreasure = ((JSONBoolean)data["isgreat"]).Value;
		mIsLargeTreasure = ((JSONBoolean)data["islarge"]).Value;
		mIsTwiT = ((JSONBoolean)data["istwit"]).Value;

		mCounter = (GameObject)MRGame.Instantiate(MRGame.TheGame.treasureCardPrototype);
		TextMesh text = mCounter.GetComponentInChildren<TextMesh>();
		if (text.name == "FrontText")
		{
			StringBuilder buffer = new StringBuilder(Name.ToUpper());
			buffer.Replace(' ', '\n');
			text.text = buffer.ToString();
		}
		Sprite texture = (Sprite)Resources.Load("Textures/treasure_back", typeof(Sprite));
		SpriteRenderer[] sprites = mCounter.GetComponentsInChildren<SpriteRenderer>();
		foreach (SpriteRenderer sprite in sprites)
		{
			if (sprite.name == "BackSide")
			{
				sprite.sprite = texture;
			}
		}
	}
	
	// Update is called once per frame
	public override void Update ()
	{
		base.Update();

		Vector3 orientation = mCounter.transform.localEulerAngles;
		if (Hidden)
			orientation.y = 180f;
		else
			orientation.y = 0;
		mCounter.transform.localEulerAngles = orientation;
	}

	#endregion

	#region Members

	private bool mIsGreatTreasure;
	private bool mIsLargeTreasure;
	private bool mIsTwiT;
	private bool mHidden;

	#endregion
}
